name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build the Next.js app
        run: npm run build

      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Docker Push
        env:
          REPO: busgo/frontend
        run: |
          docker build -t busgo/frontend .
          docker tag busgo/frontend  docker.io/busgo/frontend:latest
          docker push docker.io/busgo/frontend:latest

      - name: Docker Pull & Run from Docker Hub
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_ADDRESS}}
          username: ubuntu
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
            sudo docker pull busgo/frontend:latest
            sudo docker stop busgo/frontend || true
            sudo docker rm busgo/frontend || true
            sudo docker run -d -p 3000:3000 --name busgo/frontend busgo/frontend:latest
