name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: rm -rf node_modules -rf npm.lock && npm install --frozen-lockfile

      - name: Build the Next.js app
        run: npm run build

      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Docker Push
        env:
          REPO: busgo/frontend
        run: |
          docker build -t busgo/frontend .
          docker tag busgo/frontend  docker.io/busgo/frontend:latest
          docker push docker.io/busgo/frontend:latest
      - name: Docker Pull & Run from Docker Hub
        uses: appleboy/ssh-action@master
        with:
          host: ec2-52-28-91-40.eu-central-1.compute.amazonaws.com
          username: ubuntu
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
              sudo docker pull busgo/frontend:latest
              sudo docker stop frontend || true
              echo "Container stopped"
              sudo docker rm frontend  || true
              echo "Container removed"
              sudo docker run -d --name frontend -p 3000:3000 busgo/frontend:latest